using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionSwitch(CCVars.ChatEnableColorName, EnableColorNameToggleStatusButton);
        Control.AddOptionSwitch(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyToggleStatusButton);
        Control.AddOptionSwitch(CCVars.ReducedMotion, ReducedMotionToggleStatusButton);
        Control.AddOptionSwitch(CCVars.DisableAiStatic, DisableAiStaticToggleStatusButton);
        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);
        Control.AddOptionSwitch(CCVars.ChatAutoFillHighlights, AutoFillHighlightsToggleStatusButton);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        Control.AddOptionSwitch(CCVars.AccessibilityClientCensorNudity, CensorNudityToggleStatusButton);

        Control.Initialize();
    }
}

