using System.Linq;
using Content.Client.UserInterface.Screens;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColorRow.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };

        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);

        Control.AddOptionSwitch(CVars.DiscordEnabled, DiscordRichToggleStatusButton);
        Control.AddOptionSwitch(CCVars.ShowOocPatronColor, ShowOocPatronColorToggleStatusButton);
        Control.AddOptionSwitch(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadToggleStatusButton);
        Control.AddOptionSwitch(CCVars.HudHeldItemShow, ShowHeldItemToggleStatusButton);
        Control.AddOptionSwitch(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsToggleStatusButton);
        Control.AddOptionSwitch(CCVars.OpaqueStorageWindow, OpaqueStorageWindowToggleStatusButton);
        Control.AddOptionSwitch(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesToggleStatusButton);
        Control.AddOptionSwitch(CCVars.ChatFancyNameBackground, FancyNameBackgroundsToggleStatusButton);
        Control.AddOptionSwitch(CCVars.StaticStorageUI, StaticStorageUIToggleStatusButton);

        Control.Initialize();
    }
}
