using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class OptionRow : Control
{
    private bool _disabledStyle;

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    public string? Description
    {
        get => DescriptionLabel.Text;
        set
        {
            DescriptionLabel.Text = value;
            DescriptionLabel.Visible = !string.IsNullOrEmpty(value);
        }
    }

    public bool DisabledStyle
    {
        get => _disabledStyle;
        set
        {
            _disabledStyle = value;
            UpdateDisabledStyle();
        }
    }

    public OptionRow()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = ContentContainer.Children;
        DescriptionLabel.Visible = false;
    }

    protected override void OnThemeUpdated()
    {
        base.OnThemeUpdated();

        RowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Theme.ResolveColorOrSpecified("slotColor", Color.FromHex("#0f1215")),
            BorderColor = Theme.ResolveColorOrSpecified("slotOutline", Color.FromHex("#333850")),
            BorderThickness = new Thickness(1),
        };

        UpdateDisabledStyle();
    }

    private void UpdateDisabledStyle()
    {
        var color = _disabledStyle
            ? Theme.ResolveColorOrSpecified("disabledFore", Color.FromHex("#8A8A8A"))
            : Color.White;

        TitleLabel.Modulate = color;
        DescriptionLabel.Modulate = color;
        ContentContainer.Modulate = _disabledStyle ? Color.FromHex("#FFFFFF80") : Color.White;
    }
}
