using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class OptionRow : Control
{
    private bool _disabledStyle;
    private bool _contentBelowLabel;

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    public string? Description
    {
        get => DescriptionLabel.Text;
        set
        {
            DescriptionLabel.Text = value;
            DescriptionLabel.Visible = !string.IsNullOrEmpty(value);
        }
    }

    public bool DisabledStyle
    {
        get => _disabledStyle;
        set
        {
            _disabledStyle = value;
            UpdateDisabledStyle();
        }
    }

    public bool ContentBelowLabel
    {
        get => _contentBelowLabel;
        set
        {
            _contentBelowLabel = value;
            UpdateLayoutMode();
        }
    }

    public OptionRow()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = ContentContainer.Children;
        DescriptionLabel.Visible = false;
        UpdateLayoutMode();
        ApplyTheme();
    }

    public void AddContent(Control control)
    {
        ContentContainer.AddChild(control);
    }

    protected override void OnThemeUpdated()
    {
        base.OnThemeUpdated();
        ApplyTheme();
    }

    private void ApplyTheme()
    {
        RowPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Theme.ResolveColorOrSpecified(
                "optionsRowColor",
                Theme.ResolveColorOrSpecified("slotColor", Color.FromHex("#1F242E"))),
            BorderColor = Theme.ResolveColorOrSpecified("slotOutline", Color.FromHex("#333850")),
            BorderThickness = new Thickness(1),
        };

        UpdateDisabledStyle();
    }

    private void UpdateLayoutMode()
    {
        RowContainer.Orientation = _contentBelowLabel
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;

        LabelContainer.MinWidth = _contentBelowLabel ? 0 : 128;
        LabelContainer.SizeFlagsStretchRatio = _contentBelowLabel ? 1f : 0.45f;
        ContentContainer.SizeFlagsStretchRatio = _contentBelowLabel ? 1f : 0.55f;
    }

    private void UpdateDisabledStyle()
    {
        var color = _disabledStyle
            ? Theme.ResolveColorOrSpecified("disabledFore", Color.FromHex("#8A8A8A"))
            : Color.White;

        TitleLabel.Modulate = color;
        DescriptionLabel.Modulate = color;
        ContentContainer.Modulate = _disabledStyle ? Color.FromHex("#FFFFFF80") : Color.White;
    }
}
