using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for color sliders in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionColorSlider"/>
[GenerateTypedNameReferences]
public sealed partial class OptionColorSlider : Control
{
    private bool _showTitle = true;

    public OptionColorSlider()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// The text describing what this slider affects.
    /// </summary>
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    /// <summary>
    /// The example text showing the current color of the slider.
    /// </summary>
    public string? Example
    {
        get => ExampleLabel.Text;
        set => ExampleLabel.Text = value;
    }

    public bool ShowTitle
    {
        get => _showTitle;
        set
        {
            _showTitle = value;
            TitleLabel.Visible = value;
        }
    }
}
