using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class OptionSection : Control
{
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    public OptionSection()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = RowContainer.Children;
    }

    public void AddRow(Control control)
    {
        RowContainer.AddChild(control);
    }

    protected override void OnThemeUpdated()
    {
        base.OnThemeUpdated();

        var outline = Theme.ResolveColorOrSpecified("slotOutline", Color.FromHex("#333850"));

        SectionPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Theme.ResolveColorOrSpecified(
                "optionsSectionColor",
                Theme.ResolveColorOrSpecified("slotColorDark", Color.FromHex("#171823"))),
            BorderColor = outline,
            BorderThickness = new Thickness(1),
        };

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Theme.ResolveColorOrSpecified("slotSelectedGold", Color.FromHex("#e6b812")),
        };
    }
}
