using Content.Shared.Disposal.Components;
using Content.Shared.Disposal.Mailing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Disposal.Mailing.SharedDisposalTaggerComponent;

namespace Content.Client.Disposal.Tube
{
    /// <summary>
    /// Client-side UI used to control a <see cref="Shared.Disposal.Mailing.SharedDisposalTaggerComponent"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class DisposalTaggerWindow : DefaultWindow
    {
        public DisposalTaggerWindow()
        {
            RobustXamlLoader.Load(this);

            TagInput.IsValid = tag => TagRegex.IsMatch(tag);
        }


        public void UpdateState(DisposalTaggerUserInterfaceState state)
        {
            TagInput.Text = state.Tag;
        }
    }
}
