using Content.Client.UserInterface.Controls;
using Content.Shared.Audio.Jukebox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Audio.Components;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Audio.Jukebox;

/// <summary>
/// Provides common functionality for radar-like displays on shuttle consoles.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class JukeboxWindow : FancyWindow
{
    private readonly IEntityManager _entManager;

    public event Action? PlayMusic;
    public event Action? StopMusic;
    public event Action<ProtoId<JukeboxPrototype>>? ChangeTrack;

    private EntityUid? _stream;

    public JukeboxWindow(IEntityManager entManager)
    {
        _entManager = entManager;
    }

    public void SetTrack(EntityUid stream, ProtoId<JukeboxPrototype> proto)
    {
        PlaybackLabel.Text = "00:00 / 00:00";

        if (_entManager.TryGetComponent(stream, out AudioComponent? audioComp))
        {
            var audioSystem = _entManager.System<SharedAudioSystem>();

            _stream = stream;

            TrackLabel.Text = Loc.GetString($"jukebox-track-{proto.Id}");
            PlaybackSlider.MaxValue = (float) audioSystem.GetAudioLength(audioComp.FileName).TotalSeconds;
        }
        else
        {
            TrackLabel.Text = Loc.GetString("jukebox-track-unknown");
            PlaybackSlider.MaxValue = 1f;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_entManager.TryGetComponent(_stream, out AudioComponent? audioComp))
        {
            var audioSystem = _entManager.System<SharedAudioSystem>();
            PlaybackLabel.Text = $"{audioComp.PlaybackPosition:0.00} / {audioSystem.GetAudioLength(audioComp.FileName):0.00}";
            PlaybackSlider.Value = audioComp.PlaybackPosition;
        }
    }

    public void BuildList(EntityUid uid, IPrototypeManager protoManager)
    {
        MusicList.DisposeAllChildren();

        if (!_entManager.TryGetComponent(uid, out JukeboxComponent? jukebox))
            return;

        var playGroup = new ButtonGroup();

        foreach (var proto in protoManager.EnumeratePrototypes<JukeboxPrototype>())
        {
            var entry = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal
            };

            entry.AddChild(new Label()
            {
                Text = Loc.GetString($"jukebox-track-{proto.ID}"),
            });

            var playButton = new Button()
            {
                Text = Loc.GetString("jukebox-play"),
                Group = playGroup,
            };

            entry.AddChild(playButton);

            if (jukebox.SelectedProto == proto.ID)
            {
                playButton.Pressed = true;
            }

            playButton.OnPressed += args =>
            {
                ChangeTrack?.Invoke(proto.ID);
            };

            MusicList.AddChild(entry);
        }
    }
}
